spring:
  application:
    name: simple-invest
  datasource:
    initialization-mode: never
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
    hikari:
      jdbc-url: jdbc:h2:~/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    property-naming-strategy: SNAKE_CASE      
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kakaopay.investing.model
  
server:
  shutdown: graceful
  port: 8080
    